server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
client:
  user:
    to: 0.0.0.0:9001
  favorite:
    to: 0.0.0.0:9002
data:
  mysql:
    driver: mysql
    dsn: "root:xxxxxx@tcp(0.0.0.0:3306)/atreus?charset=utf8mb4&parseTime=True&loc=Local"
  redis:
    comment_db: 1
    addr: 0.0.0.0:6379
    password: "XXXXXX"
    read_timeout: 0.2s
    write_timeout: 0.2s
    TTL: 1000
jwt:
  http:
    token_key: "XXXXX"
  grpc:
    token_key: "XXXXX"
minio:
  endpointExtra: 0.0.0.0:19000
  endpointIntra: 0.0.0.0:19000
  accessKeyId: "xxxxx"
  accessSecret: "xxxxx"
  useSSL: false
  bucketName: "oss"