server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
client:
  user:
    to: 0.0.0.0:9001
  favorite:
    to: 0.0.0.0:9002
data:
  mysql:
    driver: mysql
    dsn: "atreus:TooManySource114@tcp(rm-cn-zsk3cjj6m001c62o.rwlb.rds.aliyuncs.com:3306)/atreus?charset=utf8mb4&parseTime=True&loc=Local"
  redis:
    comment_db: 1
    addr: toomanysource.redis.rds.aliyuncs.com:6379
    password: "TooManySource114"
    read_timeout: 0.2s
    write_timeout: 0.2s
    TTL: 1000
jwt:
  http:
    token_key: "AtReUs"
  grpc:
    token_key: "ToOMaNySoUrCe"
minio:
  endpointExtra: 43.138.192.7:19000
  endpointIntra: 10.0.8.7:19000
  accessKeyId: "Z4eVNROPGg9y1xZVzcSZ"
  accessSecret: "earG4JNVcDu2fM9246VyXmzsJ5H3OJvTesnOgPmN"
  useSSL: false
  bucketName: "oss"