server:
  http:
    addr: 0.0.0.0:8005
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9005
    timeout: 1s
client:
  relation:
    to: 0.0.0.0:9004
data:
  database:
    driver: mysql
    source: root:toomanysource@tcp(127.0.0.1:3306)/atreus?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
jwt:
  http:
    token_key: "AtReUs"
  grpc:
    token_key: "ToOMaNySoUrCe"
